logging:
  level:
    com.bonc.msiopeventdispatch.mapper: DEBUG
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 1000MB
      max-file-size: 200MB
      file-size-threshold: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-password: druid
        login-username: druid
        reset-enable: true
        url-pattern: /druid/*
    password: bonc!QAZ
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://129.204.107.12:3306/iop_public?characterEncoding=UTF-8&serverTimezone=GMT%2B8&maxAllowedPacket=10240
    username: root
  kafka:
    bootstrap-servers: 127.0.0.1:9092 #指定kafka server的地址，集群配多个，中间，逗号隔开
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: event_consumer_group #群组ID
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.bonc.msiopeventdispatch.vo
#pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





